InnoGotchi.MVC/InnoGotchi.MVC/Controllers/AutenticationController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using InnoGotchi.MVC.Contracts.Services;
using InnoGotchi.MVC.Models;
using InnoGotchi.MVC.Models.User;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using IAuthenticationService = InnoGotchi.MVC.Contracts.Services.IAuthenticationService;

namespace InnoGotchi.MVC.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly IAuthenticationService _authenticationService;
        private readonly IUserService _userService;
        private readonly IValidator<UserForRegistrationDto> _userForRegvalidator;

        public AuthenticationController(IAuthenticationService authenticationService,
            IValidator<UserForRegistrationDto> userForRegvalidator,
            IUserService userService)
        {
            _authenticationService = authenticationService;
            _userForRegvalidator = userForRegvalidator;
            _userService = userService;
        }

        [HttpGet]
        public IActionResult SignIn()
        {
            return View(new UserForAuthenticationDto());
        }

        [HttpGet]
        public IActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Registration(UserForRegistrationDto userForReg)
        {
            var result = await _userForRegvalidator.ValidateAsync(userForReg);
            if (!result.IsValid)
            {
                result.AddToModelState(ModelState);
                return View(userForReg);
            }
            var userForAuth = await _authenticationService.RegisterUserAsync(userForReg, ModelState);
            if (!ModelState.IsValid)
            {
                return View(userForReg);
            }

            return View("~/Views/Authentication/SignIn.cshtml", userForAuth);
        }

        [HttpPost]
        public async Task<IActionResult> SignIn(UserForAuthenticationDto userForAuth)
        {
            var token = await _authenticationService.SignInAsync(userForAuth, ModelState);

            if (!ModelState.IsValid)
            {
                return View(userForAuth);
            }

            var claimPrincipal = CreateClaimsPrincipal(token);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimPrincipal);

            Response.Cookies.Append("jwt", token.AccessToken);

            var user = await _userService.GetUserInfoDtoAsync(token.AccessToken, token.UserId.ToString());

            Response.Cookies.Append("name", user.FirstName);
            Response.Cookies.Append("avatar", user.AvatarPath);

            return RedirectToAction("FarmOverview", "Farm");
        }

        [HttpPost]
        public async Task<IActionResult> LogOut()
        {
            Response.Cookies.Delete("jwt");
            Response.Cookies.Delete("name");
            Response.Cookies.Delete("avatar");
            Response.Cookies.Delete("my-farm-id");

            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Index", "Home");
        }

        private ClaimsPrincipal CreateClaimsPrincipal(AccessTokenDto accessModel)
        {
            var claims = new List<Claim>
            {
                new Claim("Id", accessModel.UserId.ToString())
            };
            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var claimPrincipal = new ClaimsPrincipal(claimsIdentity);

            return claimPrincipal;
        }
    }
}

InnoGotchi.MVC/InnoGotchi.MVC/Controllers/UserController.cs
using AutoMapper;
using InnoGotchi.MVC.Contracts.Services;
using InnoGotchi.MVC.Models.User;
using InnoGotchi.MVC.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InnoGotchi.MVC.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IMapper _mapper;

        public UserController(IUserService userService, IMapper mapper)
        {
            _userService = userService;
            _mapper = mapper;
        }

        private (string, string) GetRequiredParameters()
        {
            var jwt = Request.Cookies["jwt"];
            var userId = User.Claims.First(c => c.Type == "Id").Value;
            return (jwt, userId);
        }

        [HttpGet]
        public async Task<IActionResult> UserProfile()
        {
            var (jwt, userId) = GetRequiredParameters();

            var userDto = await _userService.GetUserInfoDtoAsync(jwt, userId);

            var userViewModel = new UserViewModel()
            {
                UserInfo = userDto,
                UserInfoForUpdate = _mapper.Map<UserInfoForUpdateDto>(userDto)
            };

            return View(userViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateUserInfo(UserViewModel userVM)
        {
            var (jwt, userId) = GetRequiredParameters();

            await _userService.UpdateUserInfoAsync(jwt, userId, userVM.UserInfoForUpdate);

            Response.Cookies.Append("name", userVM.UserInfoForUpdate.FirstName);

            return RedirectToAction("UserProfile");
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(UserViewModel userVM)
        {
            var (jwt, userId) = GetRequiredParameters();

            await _userService.ChangePasswordAsync(jwt, userId, userVM.PasswordChanging);

            return RedirectToAction("UserProfile");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateAvatar(UserViewModel userVM)
        {
            var (jwt, userId) = GetRequiredParameters();

            await _userService.UpdateAvatarAsync(jwt, userId, userVM.Avatar);
            var path = User.Claims.First(c => c.Type == "Id").Value + "-" + userVM.Avatar.FileName;
            Response.Cookies.Append("avatar", path);

            return RedirectToAction("UserProfile");
        }
    }
}

InnoGotchi.MVC/InnoGotchi.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InnoGotchi.MVC.styles.css" asp-append-version="true" />
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/js.cookie.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

</head>
<body>
    <header>
        <nav class="navbar fixed-top navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InnoGotchi.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if(User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="AllInnoGotchi" asp-route-orderBy="1" asp-route-pageSize="10" asp-route-pageNumber="1">All innogotchi</a>
                            </li>                            
                        }
                    </ul>
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="User" asp-action="UserProfile">
                                    <img width="30" height="30" class="rounded-circle" src="https://localhost:7208/images/avatars/@Context.Request.Cookies["avatar"]"/>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" title="Manage">Hello, @Context.Request.Cookies["name"]!</a>
                            </li>

                            <li class="nav-item">
                                <form class="form-inline" asp-controller="Authentication" asp-action="LogOut" method="post">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Authentication" asp-action="Registration">Registration</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Authentication" asp-action="SignIn">Sign in</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-4 mt-5 pt-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - InnoGotchi.MVC / Powered by <a href="https://www.linkedin.com/in/stas-kotashevich-6504451b6/">kotofot</a>
        </div>
    </footer>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>