InnoGotchi.MVC/InnoGotchi.MVC/Models/Pet/PetDetailsDto.cs
namespace InnoGotchi.MVC.Models.Pet
{
    public class PetDetailsDto
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string HungerLevel { get; set; }
        public string ThirstyLevel { get; set; }
        public int Age { get; set; }
        public bool IsAlive { get; set; }
        public double HappinessDayCount { get; set; }
        public int Body { get; set; }
        public int Eye { get; set; }
        public int Nose { get; set; }
        public int Mouth { get; set; }
    }
}

InnoGotchi.MVC/InnoGotchi.MVC/Models/Pet/PetForCreationDto.cs
namespace InnoGotchi.MVC.Models.Pet
{
    public class PetForCreationDto
    {
        public string Name { get; set; }
        public int Body { get; set; }
        public int Eye { get; set; }
        public int Nose { get; set; }
        public int Mouth { get; set; }
    }
}

InnoGotchi.MVC/InnoGotchi.MVC/Models/Pet/PetForUpdateDto.cs
namespace InnoGotchi.MVC.Models.Pet
{
    public class PetForUpdateDto
    {
        public string Name { get; set; }
    }
}

InnoGotchi.MVC/InnoGotchi.MVC/Models/Pet/PetOverviewDto.cs
namespace InnoGotchi.MVC.Models.Pet
{
    public class PetOverviewDto
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string HungerLevel { get; set; }
        public string ThirstyLevel { get; set; }
        public int Age { get; set; }
        public double HappinessDayCount { get; set; }
        public bool IsAlive { get; set; }
    }
}

InnoGotchi.MVC/InnoGotchi.MVC/Models/Pet/PetPagingDto.cs
using InnoGotchi.MVC.RequestFeatures;

namespace InnoGotchi.MVC.Models.Pet
{
    public class PetPagingDto
    {
        public IEnumerable<PetDetailsDto> PetDetails { get; set; }
        public MetaData MetaData { get; set; }
    }
}

InnoGotchi.MVC/InnoGotchi.MVC/ViewModels/PetDetailsViewModel.cs
using InnoGotchi.MVC.Models.Pet;

namespace InnoGotchi.MVC.ViewModels
{
    public class PetDetailsViewModel
    {
        public PetDetailsDto PetDetails { get; set; }
        public PetForUpdateDto PetForUpdate { get; set; }
        public Guid FarmId { get; set; }
    }
}

InnoGotchi.MVC/InnoGotchi.MVC/Controllers/FarmController.cs
using AutoMapper;
using InnoGotchi.MVC.Contracts.Services;
using InnoGotchi.MVC.Models.Farm;
using InnoGotchi.MVC.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InnoGotchi.MVC.Controllers
{
    [Authorize]
    public class FarmController : Controller
    {
        private readonly IFarmService _farmService;
        private readonly IPetService _petService;
        private readonly IMapper _mapper;

        public FarmController(IFarmService farmService, IPetService petService, IMapper mapper)
        {
            _farmService = farmService;
            _petService = petService;
            _mapper = mapper;
        }

        private (string, string) GetRequiredParameters()
        {
            var jwt = Request.Cookies["jwt"];
            var userId = User.Claims.First(c => c.Type == "Id").Value;
            return (jwt, userId);
        }

        [HttpGet]
        public async Task<IActionResult> FarmOverview()
        {
            var (jwt, userId) = GetRequiredParameters();

            var farmDto = await _farmService.GetUserFarmOverviewAsync(jwt, userId);
            Response.Cookies.Append("my-farm-id", farmDto == null ? "" : farmDto.Id.ToString());
            var farms = await _farmService.GetFriendsFramsAsync(jwt, userId);

            return View(new FarmViewModel { FarmOverview = farmDto, FriendsFarms = farms });
        }

        [HttpGet]
        public async Task<IActionResult> FarmDetails(Guid farmId)
        {
            var (jwt, userId) = GetRequiredParameters();

            var farmDetails = await _farmService.GetFarmDetailsAsync(jwt, userId, farmId);
            var farmDetailVM = new FarmDetailsViewModel();
            if (farmDetails.Id.ToString() != Request.Cookies["my-farm-id"])
            {
                farmDetailVM.FarmDetails = farmDetails;
                return View(farmDetailVM);
            }

            var farmStatistics = await _farmService.GetFarmStatisticsAsync(jwt, userId, farmId);

            farmDetailVM.FarmDetails = farmDetails;
            farmDetailVM.FarmForUpdate = _mapper.Map<FarmForUpdateDto>(farmDetails);
            farmDetailVM.FarmStatistics = farmStatistics;

            return View(farmDetailVM);
        }

        [HttpPost]
        public async Task<IActionResult> Feed(Guid farmId, Guid petId)
        {
            var (jwt, userId) = GetRequiredParameters();

            await _petService.FeedAsync(jwt, userId, farmId, petId);

            return RedirectToAction("FarmDetails", new { farmId });
        }

        [HttpPost]
        public async Task<IActionResult> GiveADrink(Guid farmId, Guid petId)
        {
            var (jwt, userId) = GetRequiredParameters();

            await _petService.GiveADrinkAsync(jwt, userId, farmId, petId);

            return RedirectToAction("FarmDetails", new { farmId });
        }

        [HttpPost]
        public async Task<IActionResult> CreateFarm(FarmViewModel farmVM)
        {
            var (jwt, userId) = GetRequiredParameters();

            var farmDto = await _farmService.CreateFarmAsync(jwt, userId, farmVM.FarmForCreation);

            return RedirectToAction("FarmOverview");
        }

        [HttpPost]
        public async Task<IActionResult> InviteFriend(Guid farmId, FarmDetailsViewModel farmVM)
        {
            var (jwt, userId) = GetRequiredParameters();

            await _farmService.InviteFriendAsync(jwt, userId, farmId, farmVM.UserForInviting);

            return RedirectToAction("FarmDetails", new { farmId });
        }

        [HttpPost]
        public async Task<IActionResult> UpdateFarm(Guid farmId, FarmDetailsViewModel farmVM)
        {
            var (jwt, userId) = GetRequiredParameters();

            await _farmService.UpdateFarmAsync(jwt, userId, farmId, farmVM.FarmForUpdate);

            return RedirectToAction("FarmDetails", new { farmId });
        }

        [HttpPost]
        public async Task<IActionResult> CreatePet(Guid farmId, FarmDetailsViewModel farmVM)
        {
            var (jwt, userId) = GetRequiredParameters();

            await _petService.CreatePetAsync(jwt, userId, farmId, farmVM.PetForCreation);

            return RedirectToAction("FarmDetails", new { farmId });
        }
    }
}

InnoGotchi.MVC/InnoGotchi.MVC/Controllers/PetController.cs
using AutoMapper;
using InnoGotchi.MVC.Contracts.Services;
using InnoGotchi.MVC.Models.Pet;
using InnoGotchi.MVC.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InnoGotchi.MVC.Controllers
{
    [Authorize]
    public class PetController : Controller
    {
        private readonly IPetService _petService;
        private readonly IMapper _mapper;

        public PetController(IPetService petService, IMapper mapper)
        {
            _petService = petService;
            _mapper = mapper;
        }

        private (string, string) GetRequiredParameters()
        {
            var jwt = Request.Cookies["jwt"];
            var userId = User.Claims.First(c => c.Type == "Id").Value;
            return (jwt, userId);
        }

        [HttpGet]
        public async Task<IActionResult> PetDetails(Guid farmId, Guid petId)
        {
            var (jwt, userId) = GetRequiredParameters();

            var pet = await _petService.GetPetDetailsAsync(jwt, userId, farmId, petId);

            var petDetailsVM = new PetDetailsViewModel
            {
                PetDetails = pet,
                PetForUpdate = _mapper.Map<PetForUpdateDto>(pet),
                FarmId = farmId
            };

            return View(petDetailsVM);
        }

        [HttpPost]
        public async Task<IActionResult> Feed(Guid farmId, Guid petId)
        {
            var (jwt, userId) = GetRequiredParameters();

            await _petService.FeedAsync(jwt, userId, farmId, petId);

            return RedirectToAction("PetDetails", new { farmId, petId });
        }

        [HttpPost]
        public async Task<IActionResult> GiveADrink(Guid farmId, Guid petId)
        {
            var (jwt, userId) = GetRequiredParameters();

            await _petService.GiveADrinkAsync(jwt, userId, farmId, petId);

            return RedirectToAction("PetDetails", new { farmId, petId });
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePet(Guid farmId, Guid petId, PetDetailsViewModel petVM)
        {
            var (jwt, userId) = GetRequiredParameters();

            await _petService.UpdatePetAsync(jwt, userId, farmId, petId, petVM.PetForUpdate);

            return RedirectToAction("PetDetails", new { farmId, petId });
        }
    }
}

InnoGotchi.MVC/InnoGotchi.MVC/Views/Pet/PetDetails.cshtml
@model InnoGotchi.MVC.ViewModels.PetDetailsViewModel

@{
    ViewData["Title"] = "Pet details";

    var bodyPath = $"https://localhost:7208/images/bodies/body{Model.PetDetails.Body}.svg";
    var eyesPath = $"https://localhost:7208/images/eyes/eyes{Model.PetDetails.Eye}.svg";
    var nosePath = $"https://localhost:7208/images/noses/nose{Model.PetDetails.Nose}.svg";
    var mouthPath = $"https://localhost:7208/images/mouths/mouth{Model.PetDetails.Mouth}.svg";
}

<link rel="stylesheet" href="~/css/FarmOverview.css" asp-append-version="true" />

<div class="container py-3">
    <div class="d-flex flex-column">
        <div class="row">
            <div class="col-sm-1 d-flex flex-column">
                <a asp-controller="Farm" asp-action="FarmDetails" asp-route-farmId="@Model.FarmId" class="btn btn-primary">Back</a>
            </div>
            <div class="col-lg-8 align-items-center">
                <div class="card" style="width: 60rem; height: 36rem;">
                    <div class="card-body">
                        <div class="row mb-3">
                            <h5 class="card-title">
                                @Model.PetDetails.Name
                                @if (Model.PetDetails.IsAlive && Model.FarmId.ToString() == Context.Request.Cookies["my-farm-id"])
                                {
                                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                        Change
                                    </button>
                                }
                            </h5>
                            <div class="col-sm-3">

                                <p class="card-text mb-0">Hunger level: @Model.PetDetails.HungerLevel</p>
                                <p class="card-text mb-0">Thirsty level: @Model.PetDetails.ThirstyLevel</p>
                                @if (Model.PetDetails.Age == 0)
                                {
                                    <p class="card-text mb-0">Age: Newborn</p>
                                }
                                else
                                {
                                    <p class="card-text mb-0">Age: @Model.PetDetails.Age</p>
                                }
                                <p class="card-text">Happiness days count: @Model.PetDetails.HappinessDayCount</p>
                                @if (Model.PetDetails.IsAlive)
                                {
                                    <p class="card-text mb-0">Status: Alive</p>
                                    <div class="row">
                                        <form asp-controller="Pet" asp-action="Feed" asp-route-farmId="@Model.FarmId" asp-route-petId="@Model.PetDetails.Id" method="post" class="col-4">
                                            <input type="submit" class="btn btn-primary" value="Feed">
                                        </form>
                                        <form asp-controller="Pet" asp-action="GiveADrink" asp-route-farmId="@Model.FarmId" asp-route-petId="@Model.PetDetails.Id" method="post" class="col">
                                            <input type="submit" class="btn btn-primary" value="Give a drink">
                                        </form>
                                    </div>
                                }
                                else
                                {
                                    <p class="card-text mb-0">Status: Dead</p>
                                }
                            </div>
                            <div class="col-lg-9">
                                <div class="flex-column position-relative d-flex col mb-4">
                                    <img id="body" alt="error" style="max-width: 90%" data-type="@Model.PetDetails.Body" src="@bodyPath" />
                                    <img id="eyes" alt="error" style="max-width: 20%; margin-left: 32%; margin-top: 15%" class="position-absolute" src="@eyesPath" />
                                    <img id="nose" alt="error" style="max-width: 8%; margin-left: 38%; margin-top: 26%" class="position-absolute" src="@nosePath" />
                                    <img id="mouth" alt="error" style="max-width: 19%; margin-left: 33%; margin-top: 28%" class="position-absolute" src="@mouthPath" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Change pet name</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form asp-controller="Pet" asp-action="UpdatePet" asp-route-farmId="@Model.FarmId" asp-route-petId="@Model.PetDetails.Id" method="post">
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" asp-for="PetForUpdate.Name" id="recipient-name">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="Change" />
                </div>
            </form>
        </div>
    </div>
</div>

<script src="~/js/petDetails.js"></script>